version: "3.0"

services:
  swagger-ui:
    image: swaggerapi/swagger-editor
    ports:
      - 80:8080
    environment:
      - SWAGGER_FILE=api-spec.json
    volumes:
    - ./api-spec.json:/usr/share/nginx/html/api-spec.json

    